//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityProj
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cancel_Info
    {
        public int ID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<System.DateTime> CancelledTime { get; set; }
        public string Reason { get; set; }
        public string ExtraInfo { get; set; }
        public Nullable<int> BuyerID { get; set; }
    }
}
