//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityProj
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Brand { get; set; }
        public decimal OriginalPrice { get; set; }
        public decimal SalePrice { get; set; }
        public string Condition { get; set; }
        public string Status { get; set; }
        public string Description { get; set; }
        public Nullable<int> SellerID { get; set; }
        public Nullable<int> BuyerID { get; set; }
        public string Category { get; set; }
        public Nullable<int> BillStatus { get; set; }
        public Nullable<int> ViewCount { get; set; }
        public Nullable<int> OrderCondition { get; set; }
        public string Origin { get; set; }
        public string Type { get; set; }
        public string Material { get; set; }
        public string SupportPolicy { get; set; }
        public string Area { get; set; }
        public string Size { get; set; }
        public Nullable<System.DateTime> PostedTime { get; set; }
        public string Functionality { get; set; }
        public Nullable<System.DateTime> CompleteTime { get; set; }
        public Nullable<System.DateTime> BuyTime { get; set; }
        public Nullable<int> CancelLimit { get; set; }
        public Nullable<bool> CancelRefund { get; set; }
        public Nullable<bool> PayMethod { get; set; }
        public Nullable<int> selectedShippingID { get; set; }
    }
}
