//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityProj
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rating
    {
        public int SellerID { get; set; }
        public int ProductID { get; set; }
        public Nullable<int> BuyerID { get; set; }
        public string Comment { get; set; }
        public Nullable<double> Star { get; set; }
        public int RatingID { get; set; }
    }
}
